name: 编译固件

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: windows-latest
    
    
    env:
      GCC_URL: https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-mingw-w64-x86_64-arm-none-eabi.zip

    steps:
    - uses: actions/checkout@v4

    - name: 缓存 ARM 工具链
      id: cache-arm-toolchain
      uses: actions/cache@v4
      with:
        path: C:\arm-gnu-toolchain
        key: ${{ runner.os }}-arm-toolchain-${{ env.GCC_URL }}

    - name: 下载并安装 ARM 工具链
      if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Invoke-WebRequest "${{ env.GCC_URL }}" -OutFile "gcc.zip"
        Expand-Archive gcc.zip C:\arm-gnu-toolchain -Force; Remove-Item gcc.zip

    - name: 执行编译任务
      shell: cmd
      run: |
        set GCC_PATH=C:/arm-gnu-toolchain/bin
        make

    - name: 上传固件
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build/*.hex
          build/*.bin
          build/*.elf
          build/*.map
        if-no-files-found: error
